version: '3.8'
services:
  SCHOOL_API:
    image: myapp
    volumes:
      - /home/joseph/registroAlumnos/SchoolPr/config:/root/config
      - /home/joseph/registroAlumnos/SchoolPr/database:/root/database
