server:
  port: 8080
  maxReadTimeout: 15s
  maxWriteTimeout: 15s
  gracefulShutdown: 30s


database:
  url: "database/school-proyect.db"


cors:
  allowed_origins:
    - "http://localhost:4200"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "Origin"
  allow_credentials: true
  max_age: 86400 


searchEngine:
  url: "http://localhost:7700"
  api_key: MASTER_KEY